# Stage 1: Build Stage
FROM node:16-alpine AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock (or package-lock.json if you use npm) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code to the working directory
COPY . .

# Build the React project using Vite
RUN npm run build

# Stage 2: Production Stage
FROM node:16-alpine AS production

# Set the working directory in the container
WORKDIR /app

# Copy the built files from the build stage to the production stage
COPY --from=build /app/dist ./dist

# Install serve module globally
RUN npm install -g serve

# Expose port 3000 for the React Vite service
EXPOSE 3000

# Set the command to run the production version of the React Vite server using serve
CMD ["serve", "-s", "dist", "-l", "3000"]