# Use an official Python runtime as the base image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask app code to the working directory
COPY . .

# Expose port 3002 for the Flask service
EXPOSE 3002

# Set the FLASK_APP environment variable
ENV FLASK_APP=app.py

# Set the command to run the Flask server
CMD ["flask", "run", "--host=0.0.0.0", "--port=3002"]