# Use an official Node.js runtime as the base image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install npm dependencies
RUN npm install --production

# Copy the .env file to the working directory
COPY .env ./

# Copy the server code to the working directory
COPY server.js ./

# Expose port 3001 for the Socket.IO server
EXPOSE 3001

# Set the command to run the Socket.IO server
CMD ["npm", "start"]